---

dependencies:
  - role: 'rc'
    rc:
      hostname:
        base: true
        state: 'restarted'
        conf:
          hostname: '{{ hostname }}'
        when: 'not (hostname | ansible.utils.ipaddr)'
    tags: 'hostname'
