---

dependencies:
  - role: 'pkg'
    all:
      - 'bitlbee'
    pkgng:
      - 'bitlbee'
      - 'bitlbee-steam'
      - 'purple-slack'
      - 'purple-googlechat'
      - 'purple-discord'
    tags: 'bitlbee'
  - role: 'rc'
    rc:
      bitlbee:
        base: false
        conf:
          bitlbee_enable: '{{ bitlbee_ports is not mapping }}'
    tags: 'bitlbee'
