---

- name: 'include bitlbee parameters'
  include_vars: '{{ item }}'
  with_first_found:
    - files: '{{ ansible_distribution }}.yml'
      errors: 'ignore'
  tags: 'bitlbee'

- name: 'create bitlbee.conf(5)'
  template:
     src: 'bitlbee.conf.j2'
     dest: '{{ bitlbee_conf }}'
     owner: 'root'
     group: 'bitlbee'
     mode: 0440
  tags: 'bitlbee'

- import_tasks: 'rc.yml'
  when: 'ansible_distribution == "FreeBSD"'
