---

- name: 'truncate'
  copy:
    content: ''
    dest: '{{ item.path | mandatory }}'
    owner: '{{ item.owner | default("root") }}'
    group: '{{ item.group | default("wheel") }}'
    mode: '{{ item.mode | default("0644") }}'
  when: '(item.state | default()) == "empty"'
  loop: '{{ files }}'
  tags: 'files'

- name: 'chflags'
  command:
  args:
    argv:
      - 'chflags'
      - '{{ item.chflags if (item.chflags is string) else (item.chflags | unique | join(",")) }}'
      - '{{ item.path | mandatory }}'
  when: '(ansible_distribution == "FreeBSD") and (item.chflags | default())'
  loop: '{{ files }}'
  tags: 'files'
