---

- import_tasks: 'rc.yml'
  when: 'ansible_facts["system"] == "FreeBSD"'

- import_tasks: 'systemd.yml'
  when:
    - 'ansible_facts["system"] == "Linux"'
    - 'ansible_facts["service_mgr"] == "systemd"'
