---

- name: 'install gddns rc(8) script'
  copy:
    src: 'rc.d/gddns'
    dest: '/usr/local/etc/rc.d/gddns'
    owner: 'root'
    group: 'wheel'
    mode: 0555
  tags: 'gddns'

- name: 'set Google DDNS credentials'
  copy:
    content: |
      {{ gddns_username | mandatory }}
      {{ gddns_password | mandatory }}
    dest: '/usr/local/etc/gddns.conf'
    owner: 'root'
    group: 'wheel'
    mode: 0400
  tags: 'gddns'

- name: 'set gddns rc.conf(8) variables'
  sysrc:
    state: 'present'
    file: '/usr/local/etc/rc.conf.d/gddns'
    # <https://github.com/ansible/ansible/issues/17324>
    conf: |
      {
        'gddns_enable': true,
        'gddns_hostname': '{{ gddns_hostname | mandatory }}'
      }
  when: '(gddns_hostname | default()) and not (gddns_hostname | ansible.utils.ipaddr)'
  tags: 'gddns'
