---

dependencies:
  - role: 'xorg'
    xorg:
      '10-terminus':
        Files:
          - 'FontPath "{{ {
                "FreeBSD": "/usr/local/share/fonts/terminus-font/",
                "Gentoo": "/usr/share/fonts/terminus/",
              }[ansible_distribution] | mandatory }}"'
    tags: 'i3'
  - role: 'pkg'
    all:
      - 'i3'
      - 'i3status'
      - 'dmenu'
      - 'rxvt-unicode'
      - 'terminus-font'
    tags: 'i3'
