---

- hosts: '{{ target | default("pkg") }}'
  remote_user: 'ec2-user'
  become: true
  become_method: 'su'
  gather_facts: true
  tasks:
    - group_by:
        key: '{{ ansible_distribution }}'
      tags: 'always'

- hosts: '{{ target | default("pkg") }}'
  remote_user: 'ec2-user'
  become: true
  become_method: 'su'
  gather_facts: false
  roles:
    - 'common'
    - 'poudriere'
  vars_prompt:
    - name: 'bootstrap'
      prompt: 'Bootstrap poudriere?'
      default: false
      private: false
