---

- name: 'include sudo parameters'
  include_vars: '{{ item }}'
  with_first_found:
    - files: '{{ ansible_distribution }}.yml'
      errors: 'ignore'
  tags: 'sudo'

- name: 'create sudoers(5)'
  template:
    src: 'sudoers.j2'
    dest: '{{ sudo_sudoers }}'
    owner: 'root'
    group: '0'
    mode: 0400
    validate: '{{ sudo_visudo }} -cf %s'
  tags: 'sudo'
