---

- name: 'truncate'
  copy:
    content: ''
    dest: '{{ item.path | mandatory }}'
    owner: '{{ item.owner | default("root") }}'
    group: '{{ item.group | default("0") }}'
    mode: '{{ item.mode | default("0644") }}'
    attributes: '{{ (item.chattr | default()) if (ansible_system == "Linux") }}'
  when: '(item.state | default()) == "empty"'
  loop: '{{ files }}'
  tags: 'files'

- name: 'chflags'
  command:
  args:
    argv:
      - 'chflags'
      - '{{ item.chflags if (item.chflags is string) else (item.chflags | unique | join(",")) }}'
      - '{{ item.path | mandatory }}'
  when:
    - 'ansible_system == "FreeBSD"'
    - 'item.chflags | default()'
  loop: '{{ files }}'
  tags: 'files'
